swagger: '2.0'
info:
  description: Test API
  version: 1.0.0
  title: Test API
  # Team developer contact info 
  contact:
    email: heineman@wpi.edu

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: consumers
  description: Operations available to regular consumers

paths:
  /calculator:
    post:
      tags:
      - consumers
      summary: requests sum of two values
      operationId: requestSum
      description: Requests the sum of two values
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: CalculationRequest
        description: Inventory item to add
        schema:
          $ref: '#/definitions/CalculationRequest'
      responses:
        200:
          description: sum properly computed
        400:
          description: invalid input, object invalid
definitions:
  CalculationRequest:
    type: object
    required:
    - arg1
    - arg2
    properties:
      arg1:
        type: string
      arg2:
        type: string
